/**
 * Generates big, deterministic OpenAPI 3.0 documents for performance tests, the
 * local mock and `npm run fixtures:large`. Nothing big is committed to the repo.
 */
export type LargeSpecOptions = {
  /** Number of operations (4 per path: list, create, get, delete). */
  operations: number;
  /** Number of tags the operations are spread over. */
  tags?: number;
  /** Number of shared schemas in `components`. */
  schemas?: number;
  /** Extra description text per operation, to reach a given file size. */
  descriptionLength?: number;
};

const LOREM =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ';

export function generateLargeSpec({
  operations,
  tags = 20,
  schemas = 50,
  descriptionLength = 0,
}: LargeSpecOptions): Record<string, unknown> {
  const tagName = (i: number) => `group-${String(i % tags).padStart(2, '0')}`;
  const description = LOREM.repeat(Math.ceil(descriptionLength / LOREM.length)).slice(
    0,
    descriptionLength,
  );
  const op = (n: number, verb: string, extra: Record<string, unknown> = {}) => ({
    tags: [tagName(Math.floor(n / 4))],
    summary: `${verb} item ${n}`,
    operationId: `op${n}`,
    ...(description ? { description } : {}),
    ...extra,
    responses: {
      '200': {
        description: 'OK',
        content: {
          'application/json': {
            schema: { $ref: `#/components/schemas/Model${n % schemas}` },
          },
        },
      },
      default: { $ref: '#/components/responses/Error' },
    },
  });

  const paths: Record<string, unknown> = {};
  for (let n = 0; n < operations; n += 4) {
    const r = n / 4;
    const collection: Record<string, unknown> = {
      get: op(n, 'List', { parameters: [{ $ref: '#/components/parameters/Limit' }] }),
    };
    if (n + 1 < operations) collection.post = op(n + 1, 'Create');
    paths[`/resources-${r}/items`] = collection;
    if (n + 2 < operations) {
      const item: Record<string, unknown> = {
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        get: op(n + 2, 'Get'),
      };
      if (n + 3 < operations) item.delete = op(n + 3, 'Delete');
      paths[`/resources-${r}/items/{id}`] = item;
    }
  }

  const models: Record<string, unknown> = {};
  for (let i = 0; i < schemas; i++) {
    models[`Model${i}`] = {
      type: 'object',
      required: ['id'],
      properties: {
        id: { type: 'string' },
        name: { type: 'string' },
        count: { type: 'integer' },
        parent: { $ref: `#/components/schemas/Model${(i + 1) % schemas}` },
      },
    };
  }
  models.Error = { type: 'object', properties: { message: { type: 'string' } } };

  return {
    openapi: '3.0.3',
    info: {
      title: `Large API (${operations} operations)`,
      version: '1.0.0',
      description: 'Generated by tests/fixtures/largeSpec.ts.',
    },
    tags: Array.from({ length: Math.min(tags, Math.ceil(operations / 4)) }, (_, i) => ({
      name: tagName(i),
    })),
    paths,
    components: {
      schemas: models,
      parameters: {
        Limit: { name: 'limit', in: 'query', schema: { type: 'integer', maximum: 100 } },
      },
      responses: {
        Error: {
          description: 'Error',
          content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } },
        },
      },
    },
  };
}

/** The samples used by the mock and the e2e tests. */
export const LARGE_SAMPLES = {
  /** About the size of the step 1 measurement (1500 operations). */
  'large-1500': { operations: 1500 },
  /** Just below the 2 MB attachment limit. */
  'large-2mb': { operations: 2000, descriptionLength: 640 },
  /** Above the 2 MB attachment limit. */
  'too-large': { operations: 2400, descriptionLength: 800 },
} satisfies Record<string, LargeSpecOptions>;
